"""external identities and settings

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 05:13:24.968781
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=16), server_default='local', nullable=False))
        batch_op.add_column(sa.Column('external_id', sa.String(length=512), nullable=True))
        batch_op.create_index(batch_op.f('ix_groups_external_id'), ['external_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_source', sa.String(length=16), server_default='local', nullable=False))
        batch_op.add_column(sa.Column('external_id', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=16), server_default='active', nullable=False))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_external_id'), ['external_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_external_id'))
        batch_op.drop_column('last_sync_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('status')
        batch_op.drop_column('external_id')
        batch_op.drop_column('auth_source')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_external_id'))
        batch_op.drop_column('external_id')
        batch_op.drop_column('source')

    op.drop_table('app_settings')
    # ### end Alembic commands ###
