"""internal referentials and advanced role

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 06:18:56.934983
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _set_roles(roles: str) -> None:
    """Replace the role CHECK constraint. SQLite cannot alter constraints and needs a table rebuild;
    elsewhere a rebuild would fail on the foreign keys pointing to users, so the constraint is swapped in place."""
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table('users', schema=None, recreate='always') as batch_op:
            batch_op.drop_constraint('ck_users_role', type_='check')
            batch_op.create_check_constraint('ck_users_role', f"role IN ({roles})")
    else:
        op.drop_constraint('ck_users_role', 'users', type_='check')
        op.create_check_constraint('ck_users_role', 'users', f"role IN ({roles})")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referential_id', sa.String(length=64), nullable=False),
    sa.Column('row_key', sa.String(length=512), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referential_id', 'row_key', name='uq_internal_records_key')
    )
    with op.batch_alter_table('internal_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internal_records_referential_id'), ['referential_id'], unique=False)

    # ### end Alembic commands ###
    # New "advanced" role (may create internal referentials)
    _set_roles("'admin', 'advanced', 'user'")


def downgrade() -> None:
    op.execute("UPDATE users SET role = 'user' WHERE role = 'advanced'")
    _set_roles("'admin', 'user'")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internal_records_referential_id'))

    op.drop_table('internal_records')
    # ### end Alembic commands ###
